window.CRAWL_DATA = [
  {
    "source": "nhatot.com",
    "apartment_id": "155-nguyen-chi-thanh",
    "title": "Cho thuê căn hộ chung cư 155 Nguyễn chí Thanh, quận 5 ,hcm",
    "area": "60 m²",
    "furnished": null,
    "date": "3 giờ trước",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-5-tp-ho-chi-minh/132499934.htm",
    "image": null,
    "apartment_name": "155-nguyen-chi-thanh"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "155-nguyen-chi-thanh",
    "title": "Cần cho thuê căn hộ 155 Nguyễn Chí Thanh P9. Q5",
    "area": "61 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-5-tp-ho-chi-minh/132242984.htm",
    "image": null,
    "apartment_name": "155-nguyen-chi-thanh"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "carina-plaza",
    "title": "Cho thuê căn góc Lô C, 2 phòng ngủ, 2WC, 99m2 tại 1648, Carina Plaza.",
    "area": "99 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "9,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131368809.htm",
    "image": null,
    "apartment_name": "Carina Plaza",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2011,
    "address": "1648 Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "central-premium",
    "title": "Chính chủ cho thuê căn hộ Central Premium 1 phòng ngủ full giá 9.3tr",
    "area": "30 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "9,3 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132362166.htm",
    "image": null,
    "apartment_name": "Central Premium",
    "district": "Q.8",
    "km_q1": 7.1,
    "year": 2021,
    "address": "Tạ Quang Bửu, Phường 5, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "city-gate-towers",
    "title": "Có nhiều CH City Gate cho thuê, căn 2 và 3 phòng ngủ giá 7.5 triệu/tháng, có nội thất 9 triệu/tháng",
    "area": "73 m²",
    "furnished": null,
    "date": "Đăng 3 ngày trước",
    "price": "Có nhiều CH City Gate cho thuê, căn 2 và 3 phòng ngủ giá 7.5 triệu/tháng, có nội thất 9 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-16-1-city-gate-towers/co-nhieu-ch-cho-2-va-3-phong-ngu-gia-7-5-trieu-thang-co-noi-that-9-trieu-thang-pr45789775",
    "image": null,
    "apartment_name": "City Gate Towers",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2017,
    "address": "Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "city-gate-towers",
    "title": "Căn hộ City Gate mặt tiền Võ Văn Kiệt, 2pn, 2wc full nội thất giá 9 tr",
    "area": "73 m2",
    "furnished": null,
    "date": "19/05/2026",
    "price": "8 triệu 500 nghìn",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/can-ho-city-gate-mat-tien-vo-van-kiet-2pn-2wc-full-noi-that-gia-9-tr-id21965258",
    "image": null,
    "apartment_name": "City Gate Towers",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2017,
    "address": "Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "city-gate-towers",
    "title": "Cho thuê căn hộ City Gate 79m, 2pn, 2wc nhà full nội thất giá 9tr",
    "area": "74 m2",
    "furnished": null,
    "date": "19/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/cho-thue-can-ho-city-gate-79m-2pn-2wc-nha-full-noi-that-gia-9tr-id22191132",
    "image": null,
    "apartment_name": "City Gate Towers",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2017,
    "address": "Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "city-gate-towers",
    "title": "Chuyên cho thuê Căn hộ City Gate giá từ 7.5tr đến 9tr tuỳ nội thất",
    "area": "73 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "7,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/129886374.htm",
    "image": null,
    "apartment_name": "City Gate Towers",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2017,
    "address": "Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "city-gate-towers",
    "title": "Cho thuê căn hộ City gate 2pn, 2wc, full nội thất giá thuê 9 triệu",
    "area": "74 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/120150213.htm",
    "image": null,
    "apartment_name": "City Gate Towers",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2017,
    "address": "Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "CHO THUÊ CONIC RIVERSIDE 2 PHÒNG NGỦ 2 TOILET",
    "area": "73 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "9,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132121445.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "Cho thuê căn hộ Conic Riverside 1pn -2pn full NT",
    "area": "65 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "7,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131329296.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "CHO THUÊ CĂN HỘ CONIC RIVERSIDE. DT : 65m2. Giá thuê: 8.5 triệu/tháng",
    "area": "66 m²",
    "furnished": null,
    "date": "19 giờ trước",
    "price": "8,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131580458.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "RỖ HÀNG CHO THUÊ CONIC RIVERSIDE Q8 MỚI ĐA DẠNG CĂN- Ở NGAY",
    "area": "65 m²",
    "furnished": null,
    "date": "3 ngày trước",
    "price": "7,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132331082.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "Giỏ hàng cho thuê căn hộ Conic Riverside Tháng 3",
    "area": "65 m²",
    "furnished": null,
    "date": "6 ngày trước",
    "price": "6 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131151179.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "conic-riverside",
    "title": "Cho thuê căn hộ Conic Riverside, Quận 8",
    "area": "66 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "7,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132491839.htm",
    "image": null,
    "apartment_name": "Conic Riverside",
    "district": "Q.8",
    "km_q1": 7.5,
    "year": 2016,
    "address": "Tạ Quang Bửu, Phường 7, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "d-vela",
    "title": "🌹🌹🌹 CẦN CHO THUÊ CC D-Vela 2Pn 1Wc - TRỐnG Ở Liền 🌹🌹🌹",
    "area": "52 m²",
    "furnished": null,
    "date": "4 tuần trước",
    "price": "8 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132023230.htm",
    "image": null,
    "apartment_name": "D-Vela",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2019,
    "address": "1177 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "diamond-riverside",
    "title": "Chuyên cho thuê chung cư Diamond Riverside Quận 8 giá 8 triệu - 10 triệu xem nhà 24/7",
    "area": "74 m²",
    "furnished": null,
    "date": "Đăng 2 ngày trước",
    "price": "8 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-16-1-diamond-riverside/chuyen-cho-quan-8-gia-7-5-trieu-10-trieu-xem-nha-24-7-pr37659510",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "diamond-riverside",
    "title": "Chuyên cho thuê CH Diamond căn 2 và 3 phòng ngủ giá 8 đến 8.5 triệu, có nội thất giá 9 đến 10 triệu",
    "area": "73 m²",
    "furnished": null,
    "date": "Đăng hôm qua",
    "price": "8 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-16-1-diamond-riverside/chuyen-cho-ch-2-va-3-phong-ngu-gia-8-en-8-5-trieu-co-noi-that-gia-9-en-10-trieu-pr45157564",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê Diamond Riverside có nhà liền giá 8 triệu",
    "area": "73 m2",
    "furnished": null,
    "date": "19/05/2026",
    "price": "8 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/cho-thue-diamond-riverside-co-nha-lien-gia-8-trieu-id21965196",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê căn hộ Diamond Riverside, 2pn, 2wc full nội thất cao cấp",
    "area": "74 m2",
    "furnished": null,
    "date": "19/05/2026",
    "price": "10 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/cho-thue-can-ho-diamond-riverside-2pn-2wc-full-noi-that-cao-cap-id22211025",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "diamond-riverside",
    "title": "Chuyên cho thuê CH Võ Văn Kiệt loại 2pn,3pn nhà trống và nội thất.",
    "area": "73 m2",
    "furnished": null,
    "date": "22/04/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/chuyen-cho-thue-ch-vo-van-kiet-loai-2pn-3pn-nha-trong-va-noi-that-id22737197",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê chung cư Phường 16, quận 8, full nội thất giá 8 triệu",
    "area": "74 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "8 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-8/thue-can-ho-chung-cu/cho-thue-chung-cu-phuong-16-quan-8-full-noi-that-gia-8-trieu-id22189689",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "diamond-riverside",
    "title": "🔥 Còn 1 căn 🔥căn hộ Diamond Riverside 2 phòng ngủ",
    "area": "72 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132340267.htm",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê căn hộ cao cấp Diamond RiverSide P16 Q8",
    "area": "72 m²",
    "furnished": null,
    "date": "4 ngày trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132418285.htm",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê CC Diamond Riverside 2 phòng ngủ,2WC có 2 máy lạnh",
    "area": "72 m²",
    "furnished": null,
    "date": "4 ngày trước",
    "price": "8,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/130265317.htm",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "diamond-riverside",
    "title": "Cho thuê căn hộ Diamond Riverside 2pn giá 9.5tr/tháng",
    "area": "74 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "9,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132455548.htm",
    "image": null,
    "apartment_name": "Diamond Riverside",
    "district": "Q.8",
    "km_q1": 8.5,
    "year": 2020,
    "address": "1646A Võ Văn Kiệt, Phường 16, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "eco-green-saigon",
    "title": "CHO THUÊ CĂN HỘ ECO GREEN SAIGON QUẬN 7 2PN - 3PN GIÁ TỐT, VÀO Ở NGAY",
    "area": "52 m²",
    "furnished": null,
    "date": "Đăng hôm qua",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-nguyen-van-linh-phuong-tan-thuan-tay-1-eco-green-sai-gon/cho-saigon-quan-7-2pn-3pn-gia-tot-vao-o-ngay-pr45772684",
    "image": null,
    "apartment_name": "Eco Green Sài Gòn",
    "district": "Q.7",
    "km_q1": 6.5,
    "year": 2021,
    "address": "107 Nguyễn Văn Linh, Phường Tân Thuận Tây, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "felisa-riverside",
    "title": "Cho thuê căn 2 phòng cc Felisa Riversise (ngay cầu Nguyễn Tri Phương)",
    "area": "48 m²",
    "furnished": null,
    "date": "4 tuần trước",
    "price": "8,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131998875.htm",
    "image": null,
    "apartment_name": "Felisa Riverside",
    "district": "Q.8",
    "km_q1": 7.0,
    "year": 2020,
    "address": "99 Bến Bình Đông, Phường 11, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "florita",
    "title": "Mình cần cho thuê căn hộ Florita Quận 7, 80m, 2pn, căn góc, NTCB",
    "area": "80 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "14 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-can-ho-florita-quan-7-80m-2pn-can-goc-ntcb-id22738224",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "florita",
    "title": "Mình cần cho thuê căn hộ Florita Quận, 74m, 2pn, view Quận 1, 15 triệu",
    "area": "74 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "15 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-can-ho-florita-quan-74m-2pn-view-quan-1-15-trieu-id22722817",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "florita",
    "title": "Mình cần cho thuê căn hộ Florita Quận, 60m, 2pn, nội thất cơ bản, 13tr",
    "area": "60 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "13 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-can-ho-florita-quan-60m-2pn-noi-that-co-ban-13tr-id22729279",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": "Cho thuê căn hộ 2 phòng ngủ Florita 13 triệu",
    "area": "57 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132356098.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": ". Mình cần cho thuê căn hộ Florita Quận 7, 80m, 2pn, căn góc, NTCB",
    "area": "80 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "14 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132090475.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": "Sang nhượng căn hộ Florita Quận 7",
    "area": "72 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "16 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132500310.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": "Cho thuê căn hộ Florita - Tân Hưng - Quận 7",
    "area": "80 m²",
    "furnished": null,
    "date": "3 ngày trước",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132481258.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": ". Cho thuê Căn hộ Florita Quận 7 , 2pn, 2wc, đầy đủ nội thất",
    "area": "70 m²",
    "furnished": null,
    "date": "3 ngày trước",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132480535.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": "Mình cần cho thuê căn hộ Florita Quận, 74m, 2pn, 2wc,full đồ, 15 triệu",
    "area": "74 m²",
    "furnished": null,
    "date": "6 phút trước",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/130903359.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "florita",
    "title": "Căn hộ Florita, đường D1, P.Tân Hưng, Q.7, 80m2, 15tr",
    "area": "80 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132513382.htm",
    "image": null,
    "apartment_name": "Florita",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "Đường D4, Khu đô thị Him Lam, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "green-river",
    "title": "Cho thuê CH Green River 2PN 2WC Dt65m2 giá 10,5tr đầy đủ nội thất, ở liền dc, quận 8",
    "area": "Cho thuê CH Green River 2PN 2WC Dt65m2 giá 10,5tr đầy đủ nội thất, ở liền dc, quận 8",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-pham-the-hien-phuong-6-10-green-river-quan-8/cho-ch-2pn-2wc-dt65m2-gia-10-5tr-ay-u-noi-that-o-lien-dc-8-pr45774321",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "green-river",
    "title": "CHO THUÊ CĂN HỘ 2PN 2WC - 9TR5 TẠI GREEN RIVER QUẬN 8",
    "area": "65 m²",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-pham-the-hien-phuong-6-10-green-river-quan-8/cho-2pn-2wc-9tr5-tai-8-pr45759148",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "Cần cho thuê căn hộ Green River Quận 8 DT 75m2, 3pn, 2WC,Giá 10 tr",
    "area": "75 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131659871.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "Cho thuê chung cư green river quận 8,2 phòng ngủ 2wc giá 8tr5 nhà mới.",
    "area": "70 m²",
    "furnished": null,
    "date": "13 giờ trước",
    "price": "8,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131529153.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "Cần cho thuê căn hộ Green River Quận 8",
    "area": "65 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131992433.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "căn 2 phòng ngủ đầy đủ nội thất CC Green River Quận 8",
    "area": "65 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132289047.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "căn hộ đầy đủ nội thất 2 phòng ngủ chung cư Green River Quận 8",
    "area": "65 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132289075.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "Cần cho thuê căn hộ Green River Quận 8",
    "area": "61 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131398230.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "Cho thuê căn hộ Him Lam Riverside Q7, 100m, 2pn, nội thất full, 15tr",
    "area": "100 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "15 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-him-lam-riverside-q7-100m-2pn-noi-that-full-15tr-id22273411",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "Cho thuê căn hộ Him Lam Riverside Q7, 77m, 2pn, đủ nội thất, 14 triệu",
    "area": "77 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "14 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-him-lam-riverside-q7-77m-2pn-du-noi-that-14-trieu-id22658213",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "Cho thuê căn hộ Him Lam Riverside Q7, 77m, 2pn, 2wc, nội thất cơ bản",
    "area": "77 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "12 triệu 500 nghìn",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-him-lam-riverside-q7-77m-2pn-2wc-noi-that-co-ban-id22692317",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "Cho thuê căn hộ Him Lam Riverside Quận 7, 100m, 2pn, nội thất đầy đủ",
    "area": "100 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "15 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-him-lam-riverside-quan-7-100m-2pn-noi-that-day-du-id22711445",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "Cho thuê căn hộ Him Lam Riverside Quận 7, 78m, 2pn, 2wc, full nội thất",
    "area": "78 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "12 triệu 500 nghìn",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-him-lam-riverside-quan-7-78m-2pn-2wc-full-noi-that-id22218659",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "him-lam-riverside",
    "title": "cho thuê căn hộ himlam Riverside Quận 7 dt 78m2 có 2PN full NT 13 tr",
    "area": "78 m2",
    "furnished": null,
    "date": "Hôm qua",
    "price": "13 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cho-thue-can-ho-himlam-riverside-quan-7-dt-78m2-co-2pn-full-nt-13-tr-id22737122",
    "image": null,
    "apartment_name": "Him Lam Riverside",
    "district": "Q.7",
    "km_q1": 4.3,
    "year": 2015,
    "address": "Đường D1, Phường Tân Hưng, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "hung-phat-silver-star",
    "title": "CHO THUÊ CHUNG CƯ HƯNG PHÁT SILVER STAR 2pn2wc FULL NỘI THẤT 11.5tr",
    "area": "75 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "11,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-huyen-nha-be-tp-ho-chi-minh/132184933.htm",
    "image": null,
    "apartment_name": "Hưng Phát Silver Star",
    "district": "Q.7",
    "km_q1": 6.5,
    "year": 2018,
    "address": "156A Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lavida-plus",
    "title": "Cho thuê căn hộ Lavida Plus Quận 7: Căn góc 65m2, thiết kế 2PN 2PN, full nội thất - trống sẵn",
    "area": "Cho thuê căn hộ Lavida Plus Quận 7: Căn góc 65m2, thiết kế 2PN 2PN, full nội thất - trống sẵn",
    "furnished": null,
    "date": "Đăng 4 ngày trước",
    "price": "14,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-nguyen-van-linh-phuong-tan-phong-9-lavida-plus/cho-quan-7-goc-65m2-thiet-ke-2pn-2pn-full-noi-that-trong-san-pr45743653",
    "image": null,
    "apartment_name": "Lavida Plus",
    "district": "Q.7",
    "km_q1": 5.5,
    "year": 2021,
    "address": "Nguyễn Văn Linh & Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lavida-plus",
    "title": "(Cho thuê) Căn hộ Lavida Plus: 2PN2PN, 74m2, full nội thất gần RMIT, TDTU - LH 0772 605 *** gặp Phụng",
    "area": "(Cho thuê) Căn hộ Lavida Plus: 2PN2PN, 74m2, full nội thất gần RMIT, TDTU - LH 0772 605 *** gặp Phụng",
    "furnished": null,
    "date": "Đăng 4 ngày trước",
    "price": "17 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-nguyen-van-linh-phuong-tan-phong-9-lavida-plus/cho-2pn2pn-74m2-full-noi-that-gan-rmit-tdtu-lh-gap-phung-pr45424625",
    "image": null,
    "apartment_name": "Lavida Plus",
    "district": "Q.7",
    "km_q1": 5.5,
    "year": 2021,
    "address": "Nguyễn Văn Linh & Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "lavida-plus",
    "title": "Căn hộ Lavida plus",
    "area": "74 m²",
    "furnished": null,
    "date": "7 giờ trước",
    "price": "20 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132530133.htm",
    "image": null,
    "apartment_name": "Lavida Plus",
    "district": "Q.7",
    "km_q1": 5.5,
    "year": 2021,
    "address": "Nguyễn Văn Linh & Nguyễn Hữu Thọ, Phường Tân Phong, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê căn hộ chung cư Lucky Palace, Quận 6. DT: 80m2, 2PN, 2WC. Giá 13tr/th LH 0941 943 *** Thảo",
    "area": "Cho thuê căn hộ chung cư Lucky Palace, Quận 6. DT: 80m2, 2PN, 2WC. Giá 13tr/th LH 0941 943 *** Thảo",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-quan-6-dt-80m2-2pn-2wc-gia-13tr-th-lh-thao-pr45742759",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho Thuê Căn Hộ Chung Cư Lucky Palace 84m2, 2PN, Q.6, Giá: 12 tr/tháng, LH: 0903 077 ***. Được",
    "area": "Cho Thuê Căn Hộ Chung Cư Lucky Palace 84m2, 2PN, Q.6, Giá: 12 tr/tháng, LH: 0903 077 ***. Được",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-84m2-2pn-q-6-gia-12-5-tr-thang-lh-duoc-pr43924525",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê CHCC Lucky Palace, Quận 6, DT 82m2 - 2PN 2WC, nhà mới 100%, giá 12tr LH: 0899 552 ***",
    "area": "Cho thuê CHCC Lucky Palace, Quận 6, DT 82m2 - 2PN 2WC, nhà mới 100%, giá 12tr LH: 0899 552 ***",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-chcc-quan-6-dt-82m2-2pn-2wc-nha-moi-100-gia-12tr-lh-pr42618128",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê CHCC Lucky Palace, Quận 6, DT: 86m2, 2PN 2WC, giá: 12tr/tháng. LH: 0773 694 *** (Nhà đẹp)",
    "area": "Cho thuê CHCC Lucky Palace, Quận 6, DT: 86m2, 2PN 2WC, giá: 12tr/tháng. LH: 0773 694 *** (Nhà đẹp)",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-chcc-quan-6-dt-86m2-2pn-2wc-gia-12tr-thang-lh-nha-dep-pr44170965",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê CHCC Lucky Palace, Quận 6, DT 85m2-2PN 2WC, giá 12tr. LH: 0932 874 ***-Hoà",
    "area": "Cho thuê CHCC Lucky Palace, Quận 6, DT 85m2-2PN 2WC, giá 12tr. LH: 0932 874 ***-Hoà",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-chcc-quan-6-dt-82m2-2pn-2wc-full-noi-that-gia-12tr-lh-hoa-pr42703783",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê CC Lucky Palace, 80m2 2pn 2wc full nội thất giá 13tr/tháng",
    "area": "Cho thuê CC Lucky Palace, 80m2 2pn 2wc full nội thất giá 13tr/tháng",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-cc-80m2-2pn-2wc-full-noi-that-gia-13tr-thang-pr45781492",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê căn hộ chung cư Lucky Palace, Quận 6. DT: 80m2, 2PN, 2WC. Giá 13tr/th LH 0941 943 *** Thảo",
    "area": "Cho thuê căn hộ chung cư Lucky Palace, Quận 6. DT: 80m2, 2PN, 2WC. Giá 13tr/th LH 0941 943 *** Thảo",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-quan-6-dt-80m2-2pn-2wc-gia-13tr-th-lh-thao-pr45762378",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê căn hộ Lucky Palace, Quận 6, 85m2, 2pn,2wc, full nội thất, giá 15tr/th, LH 0976 028 ***",
    "area": "Cho thuê căn hộ Lucky Palace, Quận 6, 85m2, 2pn,2wc, full nội thất, giá 15tr/th, LH 0976 028 ***",
    "furnished": null,
    "date": "Đăng hôm qua",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-quan-6-85m2-2pn-2wc-full-noi-that-gia-15tr-th-lh-pr45769177",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê CC Lucky Palace 2PN, 14 triệu, 88m2, view đẹp ở Quận 6, TP.HCM",
    "area": "Cho thuê CC Lucky Palace 2PN, 14 triệu, 88m2, view đẹp ở Quận 6, TP.HCM",
    "furnished": null,
    "date": "Đăng hôm qua",
    "price": "14 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-phan-van-khoe-phuong-2-16-lucky-palace/cho-cc-2pn-14-trieu-88m2-view-ep-o-quan-6-tp-hcm-pr45766879",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê Chung cư Lucky Palace, Q.6 - Căn diện tích 88m² – 2PN, 2WC",
    "area": "88 m2",
    "furnished": null,
    "date": "14/05/2026",
    "price": "16 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-6/thue-can-ho-chung-cu/cho-thue-chung-cu-lucky-palace-q-6-can-dien-tich-88m-2pn-2wc-id22728577",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "lucky-palace",
    "title": "Cho thuê Chung cư Lucky Palace, Q.6 - 2pn 2wc - đầy đủ nội thất",
    "area": "88 m2",
    "furnished": null,
    "date": "19/05/2026",
    "price": "15 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-6/thue-can-ho-chung-cu/cho-thue-chung-cu-lucky-palace-q-6-2pn-2wc-day-du-noi-that-id22733327",
    "image": null,
    "apartment_name": "Lucky Palace",
    "district": "Q.6",
    "km_q1": 6.0,
    "year": 2017,
    "address": "50 Phan Văn Khỏe, Phường 2, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "luxcity",
    "title": "Cho thuê căn hộ 70m 2pn 2wc chung cư Luxcity quận 7 giá 11tr",
    "area": "73 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132387644.htm",
    "image": null,
    "apartment_name": "LuxCity",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "528 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "luxcity",
    "title": "Cho thuê chung cư Luxcity nhà trống 73m2 Quận 7",
    "area": "73 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132456426.htm",
    "image": null,
    "apartment_name": "LuxCity",
    "district": "Q.7",
    "km_q1": 7.0,
    "year": 2018,
    "address": "528 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Tổng hợp Q7 Riverside thiết kế 2pn-2wc máy lạnh rèm giá 9tr ,full nội thất 11tr , 0911 850 ***",
    "area": "68 m²",
    "furnished": null,
    "date": "Đăng 2 ngày trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-dao-tri-phuong-phu-thuan-3-q7-saigon-riverside/cho-lavita-charm-view-landmark-full-noi-that-lh-0932139007-xem-nha-truc-tiep-24-7-pr36195542",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "GIỎ HÀNG CHO THUÊ GIÁ CỰC RẺ GIỮA NĂM Ở Q7 RIVER SIDE 1PN-2PN-3PN GIÁ CHỈ 8TR/THÁNG LIÊN HỆ EM THU",
    "area": "55 m²",
    "furnished": null,
    "date": "Đăng 2 ngày trước",
    "price": "8 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-dao-tri-phuong-phu-thuan-3-q7-saigon-riverside/100-1pn2pn-3pn-gia-tot-lien-he-em-thanh-thu-san-key-xem-nha-ngay-pr44958143",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Thuê Q7 Riverside 1PN1WC, 2PN2WC, 3PN3WC NTCB và full đẹp chi tiết 0932 139 ***",
    "area": "53 m²",
    "furnished": null,
    "date": "Đăng 5 ngày trước",
    "price": "8 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-dao-tri-phuong-phu-thuan-3-q7-saigon-riverside/cho-nha-moi-loai-1-1-gia-chi-6tr5-lh-00968364060-de-xem-nha-pr34589289",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Gọi trước 5p xem liền: Q7 Riverside 1PN 8-10tr, 2PN 8.8-11tr, nội thất CB hoặc full LH 0939 720 ***",
    "area": "68 m²",
    "furnished": null,
    "date": "Đăng 6 ngày trước",
    "price": "8,8 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-dao-tri-phuong-phu-thuan-3-q7-saigon-riverside/duy-nhat-ch-2pn-gia-11tr-th-day-du-nt-3-may-lanh-may-nuoc-nong-rem-bep-lh-pr40982858",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "FTT Land độc quyền cho thuê nhiều căn hộ Q7 SG Riverside .",
    "area": "69 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/ftt-land-doc-quyen-cho-thue-nhieu-can-ho-q7-sg-riverside-id21957734",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình chuyên cho thuê căn hộ Q7 Saigon Riverside đường Đào Trí .",
    "area": "66 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "8 triệu 500 nghìn",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-chuyen-cho-thue-can-ho-q7-saigon-riverside-duong-dao-tri-id21879117",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Q7 Saigon Riverside cho thuê có nội thất, đúng hình đăng- đúng giá.",
    "area": "67 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/q7-saigon-riverside-cho-thue-co-noi-that-dung-hinh-dang-dung-gia-id22073512",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Nắm nhiều căn Q7 SG riverside cho thuê, mới hoàn thiện nội thất đẹp.",
    "area": "73 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/nam-nhieu-can-q7-sg-riverside-cho-thue-moi-hoan-thien-noi-that-dep-id22073577",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình có căn Q7 Saigon Riverside 2pn hoàn thiện cơ bản cần cho thuê.",
    "area": "67 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-co-can-q7-saigon-riverside-2pn-hoan-thien-co-ban-can-cho-thue-id21879126",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cần cho thuê Q7 Saigon Riverside, nhiều căn để quý khách lựa chọn",
    "area": "66 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-q7-saigon-riverside-nhieu-can-de-quy-khach-lua-chon-id21875609",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Q7 Riverside căn 2pn góc 3 mặt đủ nội thất đẹp giá 12tr/tháng .",
    "area": "73 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/q7-riverside-can-2pn-goc-3-mat-du-noi-that-dep-gia-12tr-thang-id22119257",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Q7 Saigon Riverside 2pn view sông giá 9TR",
    "area": "66 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/q7-saigon-riverside-2pn-view-song-gia-9tr-id22219189",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Q7 SAIGON RIVERSIDE sẵn các căn 1-2-3pn vào ở được ngay .",
    "area": "64 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/q7-saigon-riverside-san-cac-can-1-2-3pn-vao-o-duoc-ngay-id22692962",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Chính chủ cho thuê căn 2pn có nội thất nhà mới 100% .",
    "area": "66 m2",
    "furnished": null,
    "date": "22/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/chinh-chu-cho-thue-can-2pn-co-noi-that-nha-moi-100-id22084339",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "q7-saigon-riverside",
    "title": "Cho thuê 2pn2wc 67m2 Q7 Saigon Riverside - Giá thuê: 9.3 triệu",
    "area": "67 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "9,3 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132384603.htm",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "q7-saigon-riverside",
    "title": "🔥 CẬP NHẬT GIỎ HÀNG CHO THUÊ MỚI NHẤT- GIÁ TỐT - Q7 SAIGON RIVERSIDE C",
    "area": "70 m²",
    "furnished": null,
    "date": "13 giờ trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132572252.htm",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "q7-saigon-riverside",
    "title": "🔥 CẬP NHẬT GIỎ HÀNG CHO THUÊ MỚI NHẤT- GIÁ TỐT - Q7 SAIGON RIVERSIDE C",
    "area": "75 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132185937.htm",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "remax-plaza",
    "title": "🔥Cho thuê căn hộ 2pn 2wc remax plaza quận 6",
    "area": "94 m²",
    "furnished": null,
    "date": "12 phút trước",
    "price": "13,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132529308.htm",
    "image": null,
    "apartment_name": "remax-plaza"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "starlight-riverside",
    "title": "10TR! CHO THUÊ CH STARLIGHT 72M2 FULL NT",
    "area": "72 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/130408870.htm",
    "image": null,
    "apartment_name": "Starlight Riverside",
    "district": "Q.6",
    "km_q1": 7.0,
    "year": 2018,
    "address": "241/42 Nguyễn Văn Luông, Phường 11, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "tara-residence",
    "title": "Cho thuê chung cư Tara Residence",
    "area": "85 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132176067.htm",
    "image": null,
    "apartment_name": "Tara Residence",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1A Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "tara-residence",
    "title": "CHO THUÊ CĂN HỘ TARA RESIDENCE Q8",
    "area": "75 m²",
    "furnished": null,
    "date": "39 phút trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132260560.htm",
    "image": null,
    "apartment_name": "Tara Residence",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1A Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "tara-residence",
    "title": "Căn hộ 2Pn có máy lạnh, rèm, cc Tara Residence",
    "area": "81 m²",
    "furnished": null,
    "date": "4 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132046803.htm",
    "image": null,
    "apartment_name": "Tara Residence",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1A Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "tara-residence",
    "title": "Cho thuê căn hộ Tara Residence Q8 ✅ DT 78m2,2 phòng ngủ ,2wc ✅ Nhà có",
    "area": "78 m²",
    "furnished": null,
    "date": "6 giờ trước",
    "price": "9 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132531743.htm",
    "image": null,
    "apartment_name": "Tara Residence",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1A Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "the-pegasuite-1",
    "title": "DUPLEX 2PN, 2WC, 85m2 tại The Pegasuite 2, 16 triệu VND, Hot!",
    "area": "DUPLEX 2PN, 2WC, 85m2 tại The Pegasuite 2, 16 triệu VND, Hot!",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "16 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-pho-ta-quang-buu-phuong-6-10-the-pegasuite-2/duplex-2pn-2wc-85m2-tai-2-16-trieu-vnd-hot-pr45773838",
    "image": null,
    "apartment_name": "The Pegasuite 1",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1002 Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "the-pegasuite-1",
    "title": "Chính chủ cho thuê CH The Pegasuite - Tạ Quang Bửu Q8, full nội thất",
    "area": "75 m²",
    "furnished": null,
    "date": "16 giờ trước",
    "price": "14 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131126649.htm",
    "image": null,
    "apartment_name": "The Pegasuite 1",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1002 Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "the-pegasuite-1",
    "title": "Cho thuê The Pegasuite Quận 8",
    "area": "68 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132453656.htm",
    "image": null,
    "apartment_name": "The Pegasuite 1",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1002 Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "the-pegasuite-1",
    "title": "CHO THUÊ THE PEGASUITE FULL NT ĐẦY ĐỦ",
    "area": "68 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132576454.htm",
    "image": null,
    "apartment_name": "The Pegasuite 1",
    "district": "Q.8",
    "km_q1": 6.8,
    "year": 2019,
    "address": "1002 Tạ Quang Bửu, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Giá RẺ cho thuê Topaz City 73m2 2Phòng 2WC đầy đủ nội thất 11Tr500",
    "area": "73 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "11,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/129071500.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Giá Tốt cho thuê chung cư Topaz City 70m2 2Phòng Đầy Đủ Nội Thất 11Tr5",
    "area": "73 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "11,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131745209.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Căn hộ Topaz City Q.8 70m2 2pn 2wc",
    "area": "70 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132255150.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Cho thuê gấp căn hộ cao cấp Topaz city 2 phòng nhà trống 10tr",
    "area": "70 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132273747.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Chính chủ cần cho thuê chcc Topaz city 2 phòng nhà trống 10tr",
    "area": "70 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132231404.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Topaz City Q8 : căn 2pn trống 9,5tr/th - Full Nt 12tr/th xem nhà được",
    "area": "70 m²",
    "furnished": null,
    "date": "5 giờ trước",
    "price": "9,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132606878.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Giá rẻ cho thuê Topaz City 70m2 2Phòng 2WC đầy đủ nội thất 11Tr500",
    "area": "70 m²",
    "furnished": null,
    "date": "7 ngày trước",
    "price": "11,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/129041123.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Cho thuê nhà trống chung cư Topaz City - Giá thuê 9,5 triệu",
    "area": "73 m²",
    "furnished": null,
    "date": "8 giờ trước",
    "price": "9,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132593327.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-city",
    "title": "Giá Rẻ cho thuê căn hộ Topaz City 70m2 2Phòng Đầy Đủ Nội Thất 11Tr500",
    "area": "70 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "11,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/131583096.htm",
    "image": null,
    "apartment_name": "Topaz City",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2017,
    "address": "39 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "topaz-elite",
    "title": "Cho thuê CC Topaz Elite, 11 triệu VND, 79 m2, view đẹp, giá cực chất tại Cao Lỗ, Q8, HCM",
    "area": "Cho thuê CC Topaz Elite, 11 triệu VND, 79 m2, view đẹp, giá cực chất tại Cao Lỗ, Q8, HCM",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-cao-lo-phuong-4-15-topaz-elite/cho-cc-11-trieu-vnd-79-m2-view-ep-gia-cuc-chat-tai-q8-hcm-pr45773715",
    "image": null,
    "apartment_name": "Topaz Elite",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2020,
    "address": "129 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-elite",
    "title": "CHÍNH CHỦ CHO THUÊ CĂN TOPAZ ELITE FULL NT",
    "area": "70 m²",
    "furnished": null,
    "date": "2 giờ trước",
    "price": "12,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132537769.htm",
    "image": null,
    "apartment_name": "Topaz Elite",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2020,
    "address": "129 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-elite",
    "title": "Cho thuê căn hộ Topaz Elite 2pn2wc",
    "area": "78 m²",
    "furnished": null,
    "date": "23 giờ trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/121484693.htm",
    "image": null,
    "apartment_name": "Topaz Elite",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2020,
    "address": "129 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-elite",
    "title": "CHÍNH CHỦ CẦN CHO THUÊ CĂN TOPAZ ELITE FULL NT",
    "area": "70 m²",
    "furnished": null,
    "date": "3 ngày trước",
    "price": "12,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132458820.htm",
    "image": null,
    "apartment_name": "Topaz Elite",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2020,
    "address": "129 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "topaz-elite",
    "title": "Cho thuê căn hộ Topaz Elite- nhà trống.Giá: 10.5 triệu/ tháng",
    "area": "73 m²",
    "furnished": null,
    "date": "7 phút trước",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132314890.htm",
    "image": null,
    "apartment_name": "Topaz Elite",
    "district": "Q.8",
    "km_q1": 6.5,
    "year": 2020,
    "address": "129 Cao Lỗ, Phường 4, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê CC 2PN, 2WC, 70m2 tại Viva Riverside, giá tốt, Võ Văn Kiệt, Quận 6, HCM",
    "area": "Cho thuê CC 2PN, 2WC, 70m2 tại Viva Riverside, giá tốt, Võ Văn Kiệt, Quận 6, HCM",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/cho-cc-2pn-2wc-70m2-tai-gia-tot-quan-6-hcm-pr45500191",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "CHO THUÊ SIÊU RẺ CĂN HỘ 77M2 VIVA RIVERSIDE CHỈ 11 TRIỆU",
    "area": "77 m²",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/cho-sieu-re-77m2-chi-11-trieu-pr45669544",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "Căn hộ Viva Riverside, 3 MT Võ V Kiệt, Minh Phụng, Gia Phú, P3, Q6, 70m2, 2pn, 11tr.Linh 0902 505 ***",
    "area": "Căn hộ Viva Riverside, 3 MT Võ V Kiệt, Minh Phụng, Gia Phú, P3, Q6, 70m2, 2pn, 11tr.Linh 0902 505 ***",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/3-mt-v-minh-phung-gia-phu-p3-q6-70m2-2pn-11tr-linh-pr45780391",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "Chủ cho thuê căn hộ Viva Riverside, Q. 6 - 80m2, 2PN, 2WC, giá: 12 triệu/th, LH: 0932 874 *** - Hoà",
    "area": "Chủ cho thuê căn hộ Viva Riverside, Q. 6 - 80m2, 2PN, 2WC, giá: 12 triệu/th, LH: 0932 874 *** - Hoà",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/chu-cho-q-6-80m2-2pn-2wc-gia-12-trieu-th-lh-hoa-pr45610308",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê căn hộ Viva Riverside, Võ Văn Kiệt, Q.6, 75m2, 2PN, 2WC, Giá: 11tr/th, Lh: 0899 552 ***",
    "area": "Cho thuê căn hộ Viva Riverside, Võ Văn Kiệt, Q.6, 75m2, 2PN, 2WC, Giá: 11tr/th, Lh: 0899 552 ***",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/cho-q-6-75m2-2pn-2wc-gia-11tr-th-lh-pr45603364",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê chung cư Viva Riverside Quận 6, DT 80m2, 2PN. 2WC giá tốt: 12 triệu, LH: 0779 757 ***, Quyền",
    "area": "Cho thuê chung cư Viva Riverside Quận 6, DT 80m2, 2PN. 2WC giá tốt: 12 triệu, LH: 0779 757 ***, Quyền",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-vo-van-kiet-phuong-3-15-viva-riverside/cho-quan-6-dt-75m2-2pn-2wc-gia-tot-12-trieu-lh-quyen-pr44930953",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê căn hộ Viva Riverside, Q.6, 12tr/tháng",
    "area": "65 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132311344.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê căn hộ chung cư Viva riverside Q6",
    "area": "87 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "15 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132592906.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "cho thuê chung cư ViVa Riverside",
    "area": "69 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "12,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132267224.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "Căn hộ Viva Riverside Võ Văn Kiệt, 2 phòng ngủ, 12.5tr/tháng",
    "area": "70 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "12,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132280561.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "Căn Hộ Viva Riverside MT Võ Văn Kiệt quận 6 ( 75m2 / 2pn - 2wc )",
    "area": "75 m²",
    "furnished": null,
    "date": "2 tuần trước",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132279713.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "căn hộ 2pn 2wc full nội thất Viva riverside q6",
    "area": "80 m²",
    "furnished": null,
    "date": "3 ngày trước",
    "price": "13 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/131465809.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "Cho thuê căn hộ Viva Riverside, Q6, 70m2, 11tr",
    "area": "70 m²",
    "furnished": null,
    "date": "5 giờ trước",
    "price": "11 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/132534168.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "viva-riverside",
    "title": "📢Giỏ hàng Viva Riverside Võ Văn Kiệt quận 6",
    "area": "30 m²",
    "furnished": null,
    "date": "hôm qua",
    "price": "7 tỷ/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-6-tp-ho-chi-minh/131583995.htm",
    "image": null,
    "apartment_name": "Viva Riverside",
    "district": "Q.6",
    "km_q1": 6.5,
    "year": 2018,
    "address": "1472 Võ Văn Kiệt, Phường 3, Quận 6"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "Cần cho thuê căn hộ Green River Quận 8",
    "area": "72 m²",
    "furnished": null,
    "date": "5 ngày trước",
    "price": "8,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132552645.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "green-river",
    "title": "nhà trống ở liền được giá thuê 8tr2 mới 100% green river quận 8",
    "area": "65 m²",
    "furnished": null,
    "date": "2 giờ trước",
    "price": "8,2 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-8-tp-ho-chi-minh/132650395.htm",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "batdongsan.com.vn",
    "apartment_id": "green-river",
    "title": "Cho thuê Căn 2PN nhận nhà mới, Giá tốt, cc Green River, quận 8",
    "area": "65 m²",
    "furnished": null,
    "date": "Đăng hôm nay",
    "price": "8,2 triệu/tháng",
    "bedrooms": null,
    "link": "https://batdongsan.com.vn/cho-thue-can-ho-chung-cu-duong-pham-the-hien-phuong-6-10-green-river-quan-8/2pn-co-may-lanh-rem-gia-tot-cc-8-pr45656820",
    "image": null,
    "apartment_name": "Green River",
    "district": "Q.8",
    "km_q1": 8.0,
    "year": 2022,
    "address": "2225 Phạm Thế Hiển, Phường 6, Quận 8"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "river-panorama",
    "title": "Quận 7- Cho thuê CC River Panorama- đầy đủ nội thất",
    "area": "55 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "6 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132608738.htm",
    "image": null,
    "apartment_name": "River Panorama",
    "district": "Q.7",
    "km_q1": 7.5,
    "year": 2020,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "river-panorama",
    "title": "CHO THUÊ RIVER PANORAMA, KHU PHỨC HỢP LACASA QUẬN 7",
    "area": "57 m²",
    "furnished": null,
    "date": "5 ngày trước",
    "price": "10,5 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132563066.htm",
    "image": null,
    "apartment_name": "River Panorama",
    "district": "Q.7",
    "km_q1": 7.5,
    "year": 2020,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cần cho thuê Q7 Riverside vừa hoàn thiện nội thất mới giá 12tr.",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-q7-riverside-vua-hoan-thien-noi-that-moi-gia-12tr-id22119314",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Giỏ hàng Q7 SG Riverside phong phú 1-2-3pn,tl giá tốt nhất .",
    "area": "85 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/gio-hang-q7-sg-riverside-phong-phu-1-2-3pn-tl-gia-tot-nhat-id21962540",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cần cho thuê Q7 SG Riverside 67m2 nhà mới 100%",
    "area": "67 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "8 triệu 500 nghìn",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-q7-sg-riverside-67m2-nha-moi-100-id21965768",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Cập nhật giỏ hàng cho thuê căn hộ Q7 Saigon Riverside đường Đào Trí.",
    "area": "67 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/cap-nhat-gio-hang-cho-thue-can-ho-q7-saigon-riverside-duong-dao-tri-id21782297",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình chính chủ cho thuê Q7 SG Riverside 2pn view sông .",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-chinh-chu-cho-thue-q7-sg-riverside-2pn-view-song-id22082244",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cho thuê nhiều căn Q7 Saigon Riverside nhiều diện tích lựa chọn",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "8 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-cho-thue-nhieu-can-q7-saigon-riverside-nhieu-dien-tich-lua-chon-id22369920",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Giỏ hàng phong phú Q7 Saigon Riverside, 1-2-3pn giá tốt nhất .",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/gio-hang-phong-phu-q7-saigon-riverside-1-2-3pn-gia-tot-nhat-id21967268",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Căn hộ Q7 Saigon Riverside nhiều vị trí để lựa chọn .",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/can-ho-q7-saigon-riverside-nhieu-vi-tri-de-lua-chon-id21867828",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Chuyên cho thuê căn hộ Q7 Saigon Riverside nhiều tiện ích .",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "9 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/chuyen-cho-thue-can-ho-q7-saigon-riverside-nhieu-tien-ich-id21785758",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Chuyên giỏ hàng cho thuê căn hộ Q7 SG Riverside , cập nhật giá mới.",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/chuyen-gio-hang-cho-thue-can-ho-q7-sg-riverside-cap-nhat-gia-moi-id21957719",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Giữ khóa nhiều căn Q7 SG RIVERISIDE, xem nhà sau 10p liên hệ .",
    "area": "66 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "11 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/giu-khoa-nhieu-can-q7-sg-riveriside-xem-nha-sau-10p-lien-he-id21957691",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cho thuê căn S2.18.11 Q7 SG RIVERSIDE căn góc, nội thất đẹp .",
    "area": "73 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "12 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-cho-thue-can-s2-18-11-q7-sg-riverside-can-goc-noi-that-dep-id22073641",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "mogi.vn",
    "apartment_id": "q7-saigon-riverside",
    "title": "Mình cần cho thuê Q7 Saigon Riverside đủ nội thất chỉ vào ở .",
    "area": "53 m2",
    "furnished": null,
    "date": "28/05/2026",
    "price": "10 triệu",
    "bedrooms": null,
    "link": "https://mogi.vn/quan-7/thue-can-ho-chung-cu/minh-can-cho-thue-q7-saigon-riverside-du-noi-that-chi-vao-o-id22371207",
    "image": null,
    "apartment_name": "Q7 Saigon Riverside",
    "district": "Q.7",
    "km_q1": 8.0,
    "year": 2021,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "sunshine-diamond-river",
    "title": "CHO THUÊ PHÒNG NGỦ RIÊNG - SUNSHINE DIAMOND RIVER, QUẬN 7",
    "area": "115 m²",
    "furnished": null,
    "date": "6 ngày trước",
    "price": "7 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/131926960.htm",
    "image": null,
    "apartment_name": "Sunshine Diamond River",
    "district": "Q.7",
    "km_q1": 8.5,
    "year": 2023,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "jamona-city",
    "title": "Cho thuê căn hộ Jamona City 80m 2pn 2wc 10tr/t",
    "area": "80 m²",
    "furnished": null,
    "date": "5 ngày trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132557891.htm",
    "image": null,
    "apartment_name": "Jamona City",
    "district": "Q.7",
    "km_q1": 8.2,
    "year": 2018,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "jamona-city",
    "title": "Căn hộ Jamona City, Đào Trí, Q.7, 80m2, 10tr",
    "area": "80 m²",
    "furnished": null,
    "date": "6 ngày trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132534480.htm",
    "image": null,
    "apartment_name": "Jamona City",
    "district": "Q.7",
    "km_q1": 8.2,
    "year": 2018,
    "address": "Đường Đào Trí, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "chung-cu-ngoc-lan",
    "title": "Cho thuê chung cư Ngọc Lan đường Phú Thuận Phường Phú Thuận Quận 7",
    "area": "94 m²",
    "furnished": null,
    "date": "1 tuần trước",
    "price": "10 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-7-tp-ho-chi-minh/132456988.htm",
    "image": null,
    "apartment_name": "Chung cư Ngọc Lan",
    "district": "Q.7",
    "km_q1": 7.3,
    "year": 2011,
    "address": "Đường Phú Thuận, Phường Phú Thuận, Quận 7"
  },
  {
    "source": "nhatot.com",
    "apartment_id": "chung-cu-the-harmona",
    "title": "Chung cư The Harmona Tân Bình 75m2, 2 phòng ngủ, Full nội thất .",
    "area": "75 m²",
    "furnished": null,
    "date": "2 ngày trước",
    "price": "12 triệu/tháng",
    "bedrooms": null,
    "link": "https://www.nhatot.com/thue-can-ho-chung-cu-quan-tan-binh-tp-ho-chi-minh/132606586.htm",
    "image": null,
    "apartment_name": "Chung cư The Harmona",
    "district": "Q. Tân Bình",
    "km_q1": 5.7,
    "year": 2015,
    "address": "Quận Tân Bình, TP Hồ Chí Minh"
  }
];
